version: '3.8'

services:
  db:
    image: postgres:15
    container_name: birlik-sitesi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birlik-sitesi-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-super-secret-key-here-change-this-in-production
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: development

volumes:
  postgres_data: 