import {
  AlertTriangle,
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  MoreHorizontal,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Building,
  Home,
  Users,
  Bell,
  MessageSquare,
  Calendar,
  DollarSign,
  BarChart,
  LogOut,
  Menu,
  Eye,
  Edit,
  Shield,
  Clock,
  Hash,
  Download,
  Upload,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  billing: CreditCard,
  ellipsis: MoreVertical,
  moreHorizontal: MoreHorizontal,
  warning: AlertTriangle,
  file: File,
  fileText: FileText,
  plus: Plus,
  image: Image,
  check: Check,
  building: Building,
  home: Home,
  users: Users,
  bell: Bell,
  message: MessageSquare,
  calendar: Calendar,
  dollar: DollarSign,
  chart: BarChart,
  logout: LogOut,
  menu: Menu,
  twitter: Twitter,
  eye: Eye,
  edit: Edit,
  shield: Shield,
  clock: Clock,
  hash: Hash,
  download: Download,
  upload: Upload,
  alertTriangle: AlertTriangle,
};
